services:
  medicalappts.api:
    image: ${DOCKER_REGISTRY-}medicalapptsapi
    build:
      context: .
      dockerfile: MedicalAppts.Api/Dockerfile
    ports:
      - "5000:80" 
    depends_on:
      - sqlserver
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MedicalApptsDb;User=sa;Password=P@55w0rd_fgr_2025;Encrypt=false;TrustServerCertificate=true;
      - Redis__Host=redis
    networks:
      - apptnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@55w0rd_fgr_2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - apptnet

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - apptnet

networks:
  apptnet:
    driver: bridge
